const FIRST_FISH_CAUGHT_ACHIEVEMENT_ID = 1;

const BIGGEST_FISH_STAT_ID = 100;
const FISH_CAUGHT_STAT_ID = 101;
module.exports = {
    FIRST_FISH_CAUGHT_ACHIEVEMENT_ID,
    BIGGEST_FISH_STAT_ID,
    FISH_CAUGHT_STAT_ID
}